name: Daily Update

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: pip install -r requirements.txt

      # Get yesterday data
      - name: Téléchargement de l'historique
        uses: actions/download-artifact@v4
        with:
          name: market-history
          path: .
        continue-on-error: true

      # Script Launch
      - name: Lancement du script
        run: python newsletter_generator.py

      # New values for tomorrow
      - name: Sauvegarde de l'historique pour demain
        uses: actions/upload-artifact@v4
        with:
          name: market-history
          path: market_history.json
          retention-days: 2

      # Push to GitHub Pages
      - name: Sauvegarde et Publication
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'

          git pull --rebase origin main
          git add index.html archives/*.html
          git commit -m "Mise à jour quotidienne et archivage" || exit 0

          git push
